--- 
abstract: Yet Another HTTP::MobileAgent
author: 
  - Tokuhiro Matsuno <tokuhirom aaaatttt gmail dotottto commmmm>
build_requires: 
  Test::Warn: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-MobileAttribute
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Component: 0.15
version: 0.07
